FROM python:slim

WORKDIR /app 

COPY fastapi/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY fastapi/ .

VOLUME /app/data

COPY fastapi/docker-entrypoint.sh /app/docker-entrypoint.sh

RUN chmod +x /app/docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]