FROM ubuntu:latest

RUN apt-get update \
 && apt-get install -y apache2-utils \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "ab", "-n", "10", "-c"]

CMD [ "2", "https://jsonplaceholder.typicode.com/posts" ]